program_id = "53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io"

no_update_tracking_owners = []

[chain.neon]
id = 111
token = "HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU"

[chain.sol]
id = 112
token = "So11111111111111111111111111111111111111112"

[chain.usdt]
id = 113
token = "2duuuuhNJHUYqcnZ7LKfeufeeTBgSJdftf2zM3cZV6ym"

[chain.eth]
id = 114
token = "EwJYd3UAFAgzodVeHprB2gMQ68r4ZEbbvpoVzCZ1dGq5"