program_id = "eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU"

no_update_tracking_owners = [
    "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny",  # Chainlink oracle
    "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",   # Pyth oracle
    "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s",   # Pyth legacy oracle
]

[chain.neon]
id = 245022926
token = "89dre8rZjLNft7HoupGiyxu3MNftR577ZYu8bHe2kK7g"

[chain.sol]
id = 245022927
token = "So11111111111111111111111111111111111111112"

[chain.usdc]
id = 245022928
token = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"

[chain.usdt]
id = 245022929
token = "2duuuuhNJHUYqcnZ7LKfeufeeTBgSJdftf2zM3cZV6ym"

[chain.eth]
id = 245022930
token = "EwJYd3UAFAgzodVeHprB2gMQ68r4ZEbbvpoVzCZ1dGq5"