chain_id = 298571935
operators_whitelist = [
    "2ZGP4PnXHdK5uVrSA653TgkrQYTGk4sDCfF9WBmjpnar",
    "4UpuL9zRqZXpHcpBYU7E9pu6RMdHT8yeHr5UPiusSncS",
    "6DSERf2GtGvGEX5uL7Xbi1PMN1Fm2wVST5BMnZ5Y1FHp",
    "6HALMT8ZvZz3p9zigdUdn7bZ4ae3nrSSNNDV8qRZm22q",
    "7QFenXqFfXBLiAjxgdogefpevJyifUkhFtAKwMDnmrG8",
    "7Qv56JkvW14TqBCL9isk69v7ZDTbGCzmZe6WNqg1Du8L",
    "7fBLxCFS2peRDqqD1rZrxoQiQzMTVqBwrSCSb8Tp9pWf",
    "88uNqWyraSET85PMohRVExjSfb6tiDvQbnvQ8ajZRDgz",
    "89CLbi3gCU4HNMpxt8L52LkvFTG9ZXaQ7ywY28G2N6JX",
    "8BbcUApzuAm6Df2LSRJAMXNh5dWKU6Q8EPrEXiGcUAMz",
    "8GZQsRUck4HvW7fVeVXr2KsG3owyUg9jJ1NPVDscLeEa",
    "8GZtTTT3LH3VeBXF5pHmB7BNgFuV6vcMh9Cb4CCkhZhc",
    "8PA7YeAuDbp5rEWMfyRHoXZrEXbq3abaN75W5qaMR4vt",
    "8ZnMZNK1X39MGnjQJ7b1J1LDu66DvEKGPm8NBVV5PjTC",
    "8fpkAUKVvUMaBSrWQzdfuTxeAmFD9Rv6LdE9zxxg5U24",
    "8htbAP76dgGuJMA7MsA2ZqVWmdKoaVpV4MikEwJ8gtPb",
    "9j8jcoUuJAX5MyQYQNQpKqqGCKuKiaZQBbJGyqUFHMhM",
    "9p9MKW2YiD7mZJQ17Mo6MC2SRHuRDCMzeujeaf4tGVFK",
    "9uNpuzGY9mdRE6hd5cPtycA2UCaZwyguhCsqi3rZnxfg",
    "9wDiXTQJ52CM5b21Jm1C14HR8ERJYSzDvz4e6mAibDqW",
    "A8o2mxXSCw6ncFHPCQZ2XaqXi8fHXUS8SCtw9TrnBsxX",
    "Agh9CzEBojjkH9MEUT6NX88oQEpEkTSFdAP89jmaB4MR",
    "AxVwEdigCwRu5vo1nLPeG84ZrCW11PVYFbRJN3YVXEvh",
    "BPZAsDHvMdmvhsevdRqs3U7NF56C9ZMGyahT7gSzdFyr",
    "BqNgs2Tj7hAcWvJ9LccmGYqgGrW11VZBJCLGcAF3MUsy",
    "BvkWMHKKksoPyREWj7GfXdZRTKeuxaL6tapQvX1jgDyT",
    "ByrRzA4obx6v9fRzmEQ19skEwaiKT8BDjDABpBzK7C8Q",
    "Bz4s6aQ3GNcNEvrEdUL2Kwa3kJwkHhFfYrDmUu6Qt1v5",
    "C1P5rCmyUw7KMsgak8jRYzqcbVc7BWc4DdETKQGk6c62",
    "CujdG3fL1VrxvxWSVuyihW5TshbTJBKBvjLqERv9kmbw",
    "Cut5iYLtrZg69LKgsaPCYQoFFp5DCSaVLX3V6jE48h86",
    "D3ssfpj9nSxatqrHm1vXXcuSj93rLqDaECSF57kzBCt2",
    "DM3JWWjnh1umWPje2ZJbDEXmgWBQLxf831qqA5XVhzdd",
    "DMVefLnmEerfwwEUATirLz6MCmpbgNVTC72FCusXcVW5",
    "DiiGrCgeqFahzg3UxHyFHWmW3hLX73sLYUTCTgXnwocK",
    "Dpcpix17WSKZj8bL2wRme22fKoi8TCj3VYd4GxabmmJw",
    "EPNLCaoq3CeBbYoifUM3WcCKCQ98UTQfPPoH12u54Kqr",
    "EQ716RHdAFAk1Lgg6KzWv7GoV2LUAkbyjWu61hM7jAnU",
    "EckLkWxSxF4Yc2buxEhNiasx4sfVAg3P9dmXqRBT3zwr",
    "FEddSSVQKFJcv6rFfEFjKQg1GZwknCo8i5i2KqYMTarR",
    "FVe2eE3oH23Uc3o2bU7yosLjpLy3FbbAuC7Rk7bwwygM",
    "G1S6FPwZ3gSSqgzEVHdjgvGsKqByezpRehg7SW65mSU",
    "G3Qf3sKMuFpfDxveMkhAJC6fjyrcHTm2fxQcwTgzfDKM",
    "GRjfHd5Fam3uJ8dTiTDQ9zQEEo4Wi9gfAUTMZ4ptksDK",
    "GY79cLm1YarNS4uFoYNkzLCVnesgoyT966c2W4E2n34P",
    "GeixdG8cbQpoMDuusSi9gLV9acjLjzGyaZbexR1n1NhN",
    "GgjfqdV9awBwDUnG6NmPKLbP8YHFDy4rydzTPYzKhNab",
    "HFG92uJKpEF68JUsDXPu6vr9FTE9RCctZ8X7mDU1ke5j",
    "JDByXUUMp41yjkFiVvew3NdgKUjKLijqPtJehwjgm3Cu",
    "YmYRQRWbWqJowsPrdVFpwg1RLscUHKg9PabnWZCQsZs"
]

[token_mint]
neon_token_mint = "So11111111111111111111111111111111111111112"
decimals = 9