program_id = "NeonVMyRX5GbCrsAHnUwx1nYYoJAtskU1bWUo6JGNyG"

no_update_tracking_owners = [
    "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny",  # Chainlink oracle
    "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",   # Pyth oracle
    "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH",  # Pyth legacy oracle
]

operators_whitelist = [
    "c5mzVC8RMH424vhYXkt4GFfgZ1wT9GxsuuHiZvxu2QX",
    "EaFm5sQT62QbPVod2y31CrQMjjWTZ98aEJVau7cnpv8X",
    "Egd9CbFpE1d1MWwmRBQkMxx4MVN2pbQPq6EgHtcnmP7i",
    "EqNKVHV3Us5SydS7q1Z2q7wX98EcAM1eFrn7akHTP2BN",
    "EX4cBrK1RG2VvQZTBPstzKiUEKzmMXTDLjW9TktYRWn7",
    "F17QNqe7CV88XFwuv3zCDeZFSSLt9Us9xxGTtzmZqvg3",
    "FCYLQBV9KBgGf2tNTvAAzXBFDifsNWksirAJJy9ydekY",
    "FDJh7Ne8RCme9qcRPeVMQLRLebdm2ywz6VsSF9JcGb5H",
]

[chain.neon]
id = 245022934
token = "NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44"

[chain.sol]
id = 245022935
token = "So11111111111111111111111111111111111111112"