program_id = "NeonVMyRX5GbCrsAHnUwx1nYYoJAtskU1bWUo6JGNyG"

no_update_tracking_owners = [
    "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny",  # Chainlink oracle
    "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",   # Pyth oracle
    "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH",  # Pyth legacy oracle
]

[chain.neon]
id = 245022934
token = "NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44"
