program_id = "56XCgmB638ja7sPGN7ssCjm6JfCk95V95Rdvo4eR1ctB"

no_update_tracking_owners = []

operators_whitelist = [
"2FmkFqWJQKi3jVw4UCQiDGvR959nhzZHEFUUPHEjYtYp",
"2sj7Cf6LtN2FWT5GZnum6d7Q9cFVq6TXdRaCfU2aojm6",
"2wvuH1BuAWq6iHoHBC2dAGm797szB6e1oZA8RpCczfj8",
"31PnztACYdJDrh8JNXfTTgNv9Rj2Fj5HApHYhjkTtTJq",
"3Djm9duFUwRNjziWR7V3RLmCMBdK9WfhZYE6sTUq8EJq",
"3mWZ2Dke3Tu6vqx2rqmQZofhsAG67ZgydHAeM8QaKgfi",
"3vHBuKsAXEGH9BhQFJMubRp3Cd1MfK29gZmM2PCpPRLN",
"3wC1XHChefNpMUkxtSDj5npWq5bYxLiD4ZBRzJiZ3kNg",
"4PjdrZ5pmbHS3Gtt6XWgtTdDA2MmFwuq5Etv6tFSY1jD",
"4Vu8jqd84TZHtLZY45bCTkBvZifCV3esj2x9go6W8Lz2",
"4dapUdvTNTBbZWfVPRoa473KjLopRCVycfd6MJ93ARBY",
"58a9yCRhpATqRGL2bmFdugv1nGxRVBc1no8JwMBXinrQ",
"5BLhaf98zCkDMHx782V7r9ecEf6d2Hfs1PPjhAMv8mu9",
"5CMdEsgSkYBoE6Ty8CfDudYGMFpsphmNxhGYbZo3U5ej",
"5ChqmToeDu7wKDYBe2Y3xi74NNrMKcWawcKTRyrxKCLW",
"5FYgJBawZkCYX74JG16NPUcfRPUhdRW4ZVfrxYZAc8Gw",
"5QpV3r6h424jcogG8uw26XqPNjdXyC1N8srmoKWvTUev",
"5SFw6iXBym2t2E2GtZnCWCKBPfc8KApvMjKHDNE3fVQE",
"5YLdgryoWTP6j8xRNP1HCcTwzMLBSffGbh2UyETV2D94",
"5yhExKs9JQc4vqqmjGGz5pJa4VGFuE1MNY8KD89UiGmk",
"6tESQ2YLVAbu95vBzJiL2b8ZRtJckYeVpywX3hXQRBa4",
"77Frg2CyTcQQZRa9duRw55EUYXLyjSknffHaby9hbiWf",
"7JsCjZQj4ZXbwdRBomhJSWe7CDVGN1XJ2cd88eh97jox",
"84dgh1fp4MZQx8AbcS7ay8GgruwX7YLSdtRwziHz5HFm",
"8YucCpgASa83JXajk3pzE9KLLMRpUMPmnbmwSVSveHZZ",
"9Pb4AZ3LXDVeCKnL38C2Bp2CSRPLLJJkHQtK2CxMeVXF",
"9THSSMqH51vn9ZHDvrpSpeSGxDnHKCbicowVkUQ1jrdN",
"9W66Sp9BYSe2sHnHT2mQi2NnQtmdz7WzAy2W9K1T5vj5",
"9eJMz9ST84E47pVp5T6D9oZww4mybAksFEnBoTXsv4J1",
"ACTQGLU6z6da7JwvMqDVrQRKvxMewrtCnPbAHoNwV59M",
"ACy3S2rLQi2StrPcX9cr1gVJbHron44EDsNeKedkzQaC",
"AdR5WAox3z9CVhYWWiH3HGNWzG1XxzTssVHmUyTspHvC",
"AxQX7WsT7TqZAD9iTUkRiXtaCtGRaYjXMJVdJ5GX1VA2",
"BcuYWiNwzxeXqYwpvuAaHXp8DJxUtTfWJzDbMfysRuZd",
"CEvonukMVFdzj5RX6Zi8VLUB514xxxSaBj5Kgd15iNxo",
"CeZj4c8RbMRcwoqfCTFSTK9xuXv8WRSDacBw4Mn8TL4V",
"DGJAwC3swPwVJxsmmHV3gK6SzhDTCpZ4aWAaJjaXr3no",
"DJVY51DyTKkZhmj9ReAj6omx8HAdEfLwoyFjGq9ELG77",
"DPt6Zg36dRyLwwPinchnKDL9maivz5VTkh6SwYh2bf4H",
"DyWBpYwjnpxFK7weEkSA2E69yUhMGozXuWbQoh4TfDWe",
"E6Co38Yt2g1xKrTsKatR7ELnrYbTFRmFKp9avDmCmxdK",
"E75Z6cCHuYLXyHCRvtpzNR6gS5tdQVCjwz48rQFqV8Ci",
"Ey8rXadk5gvxsVUYkxJjCdxm7hVxpyk2UZ5gwwUmsCeQ",
"F1kUTRLHeHWZgJX1CWqpKygXsAWufzzYa24x3EUWn8CM",
"G2sRi1gLBJqqZHp6P1V5owGV5iedSNrbBxMvtyDEnYuQ",
"G8cGuKF6MSU5VxLWXsy6e5f8A6TcNUPEC3QRajFbKQ3R",
"HcWpWf89whNmbFEibcKGp3K3fZyUbPqsitSepWmxdP5J",
"J1ZahHKWdDQt7f1RT1S2dqPxfxdTbdd2zFu4TCh3Xyh3",
"J2VhXDuHcjG9gJQaK2KGyqSaejvoLpzTubeRjTH1mNvo",
"J6RLmmaN6k6PBSkRb4jd95qG6EoCS5jTLMkUZpmiFvgL",
]

[chain.neon]
id = 245022935
token = "3ZkLSMgAr6TPaPDEKCo2qTLRu2hHe65iNBo2ZkSZSRdR"
