program_id = "FXNXwbDzavyv8o7LF4pLL69sUKr47tL3b9t3vhUoc1Af"

no_update_tracking_owners = []

operators_whitelist = [
    "19NRtYxwmVn98dBxHArz7kjTke5DRfMbyj983fJcZmu",
    "29TTD8EEYALzgxHR5Acyzs36bpjJbv9a3SV92xscAdSM",
    "2CxkgkdGFYEqPeTJRrjiNVYSeGSbLje4Fzi1soa77MAx",
    "2JRnBLnwhe3oQ5Hh3NtRdVD3cNDcktRk1Xd4TWdWcNvu",
    "2PTuy2sssrK7aNgChkVmFXZUBbjvCqx7UxowGxTWS1SV",
    "2PVKSeFeYeEy8hMNwDHuvxPCvnnt4qZTni3sAQPvadkn",
    "2U7X2SrziWfHhoT9FSFbe94pz9zgi4ouSjDW7BthLZKx",
    "3J3C21cexS3ysQ6iNpJo2ueNSJnhz72amsPntvUzMTrX",
    "3Pn8MsfUipkvHVEeafE8oYT3t2hKRQfcuUQniDuVMY9m",
    "3XjrU37UiCmA6MqsvBLyzMRbC8Xgn6VnzsW5EpPifVPN",
    "3q1S49eUrTAqVU452uu73aFj6UpZ1C9uwBo7ftXrFubg",
    "41mwro55NtGLmZMcrdEKM4MV6JoEFkyCeavuZnQRQKDt",
    "4BScGLsSvAu5eTkXyaKgWBXYVu8coa8Zo7TYEW8p7jWb",
    "4Bn43sHz8NbHSHX9ShChf7Sc1DggdpAevf2eECb6Fh92",
    "4XasbV3eSwwMqsuUS4ZyjcgoxWECP5Fm9Y88ygpin4bB",
    "4cUhwr5YqapMqB5myAucxiAQMc4JJmcmbSuiiB2XL1Bn",
    "5AXd4fjU9LD2qxotvwmnAzfxm8heVREy7fcVCFT3SiV4",
    "5M1t4GUuEqCqN1FnwpU8vAniCuWp3kcYiREhrAY4Dy5i",
    "5kPKkHCSwrUzd7EVjFQcL99f8mNF2NAFtPznr4E9T8Bj",
    "6CCkYiW4AKYf4gepZTgtCtmnxtZEJzmmpN7kh2CQrxnv",
    "6Je9DcbnqiRrKbyeMFmBM1qhwjVKx843TxzquWw1AaeW",
    "6XAomgSKbsX87fUfHHqdVi8p3K4pzPx1XLKUXmdG22Xn",
    "6bNTay2SfEt4vGm878e1pMD1isMK1vZnrEqm1ewMP4MV",
    "6mxfJnfXMJ8gAx6UZfKZCVywGUfXGheoGTthHHd8kuhZ",
    "6tNgQ8tTEUAowEZHwJ6ven7ZkwL2L1omCUtpkert9dJz",
    "6xV78XYjHzvbdW5Dj9ckeFuvNfSfErcMAerogEPKKHMx",
    "71JqB5gVFKUM5uJb9vmstMxYA34h8eZDyTdsSrZMbzRT",
    "725qmLNAENPJuC6EiiXBuF2rmpEjiefiWwymoSuBetvu",
    "73tre6QACmZAr4j6F9GkaQDrHTRoJHCaJJkhwjTHBUSU",
    "7FWaPF527HPDEKHJv6MVLF72GPoTVonrqsshBSe7nvFm",
    "7Gz1WM8fuB3pzD1gfaiWWX4hsJeeip3HYjtRFLAN814F",
    "7L5Q1UWr33qm4BvBBnfiv11xPXitZipRv3rp9ogKXrwW",
    "7PVnhmN5ATXuZWYeU1pZgAPgih4aiSh1XxRjzCiuQPBy",
    "7YSvQUnfXBqgMmW5KatR6NqFrKRb1C7yd8uqGNLHmhLa",
    "87NJkVTFd5DV4CxuLcsuqX7jpTRRT7mk6tUjxjzrN35v",
    "8AWfTcDb32BUakLTdi5gE52tZJ3wvxq9361UW33ujjyD",
    "8Tgq8gjcd7qy6usZ5BHxcRB4HvaiEdVKEqz9a5Pk7UXn",
    "8a36SuHUhD2Q3WvjFR5GSJyHLHqAE8aMVg67LedXRX6A",
    "8bHYExLWFeJgRJrgrHhcKDAJ71HzyqUB9ejhjXci1rQR",
    "8ipjzfUGokjR2MVSSj23eZsfWW8xuugtyL2G3NbizoZP",
    "8u4bLPhiEiR1Fkha4s7YCsjqq5KMLYxCXDQWdrLkbzUP",
    "8xiRYRWWGBJCZrk1G4LVweCaGXYndEyyUSX55jr4KTjY",
    "9S7FZNr5pvEuw1Vfer3r9UoE77XMPemLp93TUzLFBt5R",
    "9ZeAXQgnTtxWgwxgM2uNTdJXEhuMq8S62wPt7YLJ3jYd",
    "9ddy97aV8X5FdMp9UmX9jCi9V73uJYEg57Br9zDkTPJm",
    "9fgBSsKSvCXLMm4YXbs5L9xmoRwzzahfH8SnTtUVUc2U",
    "9jai9utQmaoC6zzYN6h9oazEDs9BpQfcVzi1kNfpW7k6",
    "9wdipxaTxcUJLeQ68vSps4aTBGMBA5wxfJHsksf1gF6P",
    "9xAfZh6N6JH4zG2TF34E7fiXJPZZW7nRoAnGNyfH2CCS",
    "A66oudyXjkGyhwboSLaG9vrFpmc9hUpzkgKecBDNUpE6",
    "APMS7oZYrv7pkJxzR1nf5Yi3jbqyg5MNWo4DF6VHAUjH",
    "ATev3JbBArFv5yUCcqTbwEZnBbSTEtTDq73EgiSSMH3i",
    "AeoKAtiSomydumKFtGpH4znZGsDbQ4YnSfwT3dPAfZow",
    "Am2BUVwYQ2tXsHQi866VGM4MPVtqMyVgWuSw9zXXeViN",
    "AmHkqBpS43KcVK78SmxKcTAiAsp2GT1fEZb1KguuzQz3",
    "AnpRj8rvud7dEcFS2zDubgjBJ1nb5VjEdeBXgoMAZtuy",
    "B366Tjm9eJy4JK1Sk2UpJEivivEzZUFJhjUoa1wjqvA4",
    "B8MLT83eZ1UAJBJorqdUrvTADuyUcGpjAaEGpohggyQc",
    "BUu2VtLYLWqgwYRWeGGusB3YyGmTojFWWiPrRU4rwZ1c",
    "CBbdoKHVed1pjquFY7o2aNDddfpyowWmFvXw3HkS5ja",
    "CMX7nyyAfdi5aGirKGAeVbb91NeYz2cxgNDkvJrCs5nq",
    "Cj5js4BBqemujsEHReA2HAVvmdfPhcF8nfvtZRgD4hx2",
    "Ct5WhyPPcFso2WH88UUZGfL6WUtGZ4nTYmb4MXX2uGRe",
    "D1zmFBMgzSByKtXRapsKafcpEsGs6qVHqpY3aSTLNQkh",
    "D4Svd67PGuQ9u2Ac3oqd8tPiVAnkJococgkqMhNohzwk",
    "D6j7B7RcBwacuPrEeg5xW9PBe1FVgw1vZm9secVuZX27",
    "DJX1krqN1MECCXkjjkxWG3RRGUG2KCqhxGkNgZt5dyPT",
    "DKrXYjbEKTvzyrnCi2UCcwgiUNBmhHYTaWdc5nKCyxEN",
    "DSB77dvud255pSL7YPVxaF4AbZzaRuzh9HgZj6jsk3B6",
    "DSKnypkqswjrCJ9JbqF8EFaCnpGVsntsTswXEpJ3tmbb",
    "Dx5byNun5C4v4gr9ecJu4NcyBf1hZLNpwMw5QtxDUY8L",
    "DxveMhFdZrXLTKAvHH3wKErC4covfZDuz5eEmfJhBwnm",
    "Dyv9EoHUAjjqCyFUD1PXyNXYLkYTSHLWAmoy1JhGcxhW",
    "EGS6C4fWYpdLanufQyET9teywgXKe8SQCycoQzVm8aMf",
    "EUSLZmrcDnaoWBgoAXYVXBj31sDSaX9nfPCnnyHNzgBg",
    "Edu3tgjg3o6iLregjJZwurnrDwdGiiWQLB6xU3sBUSkK",
    "EhnJr9KRp9dPoyC5JQFBerPWgvq2MqyzU9ZLs4xNV5HH",
    "EqMsi4MevZ7DWt6FfwjcKR1SRcktWnggNPr6FqUoyu7r",
    "F4prvCbUXKwnBA3hwx66cWXCdRN279TaNzqrS7SspgWL",
    "FSYJRyuwrpcAxoHPpqjz2Ux8S7JhtNPWq99zkDCTRzbq",
    "FUEFShTD4h9pxopFfr6hbtQRcthnVBnAVRcNMm6Uv7UE",
    "FmC5QCQzxS6GRxGduSDRwX9YUbkvwJByB4M6ergAEyng",
    "FqZegLFMkV8aaUdPJ5sXTKwuUbAu4Qi52T8sCYehHRZn",
    "FqzvFoBCfkBA2SJfqWSTmMQGPzP19M5RcFV7CtLYvQaT",
    "Fr41vgv9NFXHRqeNJXy6dRzgzjzESnBFx3Bj1nAMvTuz",
    "FtyNxLnGq5f2joJKeX4gAJdCCEJaWENTGbPvsuTJXdFt",
    "FuuiKwDuhor3AYoHLsS74AcG7Z2rR2hWZ33KsbanbpAK",
    "GMFBuX8P6J3mhjdF3yE2zxkomm8dp1CBrMHQ7jSNsKGu",
    "GXfYUu3vyt6tqUaCq99AVJFZT8Mt3vkEKhze5L73Km6U",
    "GYczoDT9TRNhMyiPYYRGi3XrEG9svMm4cGNqm6umUfd2",
    "Ga7YwrkQQhmuQ8yxh7uGYSHYLk68MiiERzBxSrjUwxQX",
    "HAmRugV66CxMe1MctiJ6xsvpEmdZXiXitD9CJo3huSMW",
    "HGeHWbFDjtKbm3bCCnZnQ1N8CniK3QTXUyWpc5SSxxVj",
    "HGyb5BPhD6TMzzqUAKcYTECxypvtSKp7pjgSsaW3PMhs",
    "Hhfe7gFpc84WCwRtccBwMAUGkRenvVWRsTumxTcAQctc",
    "HrAiwkn11j1pBhSo1Snn9F7nQEMsWPi5CrxuFCwpJSju",
    "HrzfzuaK2s2QstCdhVj8wZ3VyBv9ovguiwH4E16pMPbv",
    "cDiXuaBUBw8qkL83hwmCCNGPRN8A3cbfSnzEACvs9Ld",
    "uzAuqWDmRukRzUu2oFx6rxANthGtw5XwR8bsZSqwjuP",
    "ywC69AoV9QGKpVcYFWHfyeo7cwLGUDzbAxNoziPDhkr",
]

[chain.neon]
id = 245022952
token = "BuyjTGJQWF7PbwmT6JTkhdYSbBp3WwsHKZKJVvYwYgd"

[chain.sol]
id = 245022941
token = "So11111111111111111111111111111111111111112"