[workspace]
resolver = "2"
members = [
    'api',
    'cli',
    'lib',
    'lib-interface',
    'rpc',
    'rpc-client',
    'program',
    'program-macro',
    'tracerdb-api'
]

[workspace.dependencies]
agave-feature-set = "=2.3.1"
agave-reserved-account-keys = "=2.3.1"
solana-clap-utils = "=2.3.1"
solana-cli = "=2.3.1"
solana-cli-config = "=2.3.1"
solana-client = "=2.3.1"
solana-sdk = "=2.3.1"
solana-account-decoder = "=2.3.1"
solana-compute-budget = "=2.3.1"
solana-log-collector = "=2.3.1"

solana-program = { version = "=2.3.0", default-features = false }
solana-sdk-ids = "=2.2.1"
solana-account = "=2.2.1"
solana-bn254 = "=2.2.2"

solana-address-lookup-table-interface = "2.2.2"
solana-compute-budget-interface = "2.2.2"
solana-system-interface = "1.0.0"
solana-loader-v3-interface = "5.0.0"

spl-associated-token-account = { version = "6.0", default-features = false, features = ["no-entrypoint"] }
spl-token = { version = "7.0", default-features = false, features = ["no-entrypoint"] }
ethnum = { version = "=1.5.0", default-features = false, features = ["serde"] }

[profile.test]
debug = true
