[workspace]
resolver = "2"
members = [
    'api',
    'cli',
    'lib',
    'lib-interface',
    'rpc',
    'rpc-client',
    'program',
    'program-macro',
]

[workspace.dependencies]
solana-clap-utils = "=2.1.21"
solana-cli = "=2.1.21"
solana-cli-config = "=2.1.21"
solana-client = "=2.1.21"
solana-account-decoder = "=2.1.21"
solana-program = { version = "=2.1.21", default-features = false }
solana-bn254 = "=2.1.21"
solana-sdk = "=2.1.21"
solana-sdk-ids = "=0.0.3" # the last version available for < v2.2.x
solana-program-runtime = "=2.1.21"
solana-runtime = { version = "=2.1.21", features = ["dev-context-only-utils"] }
solana-accounts-db = { version = "=2.1.21", default-features = false }
solana-bpf-loader-program = "=2.1.21"
solana-loader-v4-program = "=2.1.21"
solana-transaction-status = "=2.1.21"
solana-compute-budget = "=2.1.21"
solana-log-collector = "=2.1.21"
solana-timings = "=2.1.21"
solana-svm = "=2.1.21"
spl-associated-token-account = { version = "6.0", default-features = false, features = ["no-entrypoint"] }
spl-token = { version = "7.0", default-features = false, features = ["no-entrypoint"] }
ethnum = { version = "=1.5.0", default-features = false, features = ["serde"] }

[profile.test]
debug = true
