version: "2.1"

services:
  solana:
    image: ${EVM_LOADER_IMAGE}
    environment:
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
      - SOLANA_URL=http://solana:8899
    hostname: solana
    ports:
       - 8899
    expose:
      - "8899"
    entrypoint:
      /opt/solana/bin/solana-run-neon.sh

#  proxy:
#    container_name: proxy
#    image: proxy.py:latest
#    hostname: proxy
#    environment:
#      - SOLANA_URL=http://solana:8899
#    ports:
#      - 9090:9090
#    expose:
#      - "9090"
