version: "2.1"

services:
  solana:
    container_name: solana
    image: ${EVM_LOADER_IMAGE}
    environment:
      - SOLANA_URL=http://127.0.0.1:8899
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8003/udp"
    entrypoint:
      /opt/solana-run-neon.sh
    networks:
      - net

  neon-core-api:
    container_name: neon-core-api
    restart: unless-stopped
    hostname: neon_api
    entrypoint:
      /opt/neon-api -H 0.0.0.0:8085
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      NEON_API_LISTENER_ADDR: 0.0.0.0:8085
      SOLANA_URL: http://solana:8899
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      # operator-keypairs/id.json
      SOLANA_KEY_FOR_CONFIG: BMp6gEnveANdvSvspESJUrNczuHz1GF5UQKjVLCkAZih
      COMMITMENT: confirmed
      NEON_DB_CLICKHOUSE_URLS: "http://45.250.253.36:8123;http://45.250.253.38:8123"
    image: ${EVM_LOADER_IMAGE}
    ports:
    - "8085:8085"
    expose:
    - "8085"
    networks:
      - net
  tests:
    image: ${NEON_TESTS_IMAGE}
    environment:
      - SOLANA_URL=http://solana:8899
      - NEON_CORE_API_URL=http://neon_api:8085/api
    hostname: tests
    command: sleep infinity
    networks:
      - net

networks:
  net: